data:
  train_dir: '../data/mw/train/train_source'  # 训练集图像路径
  val_dir: '../data/mw/val/val_source'      # 验证集图像路径
  test_dir: '../data/mw/test/test_source'   # 测试集图像路径

model:
  img_size: [32, 128]
  out_char_num: 32
  out_channels: 192
  nclass: 28  # +1 for blank character
  patch_merging: 'Conv'
  embed_dim: [96, 192, 256]
  depth: [3, 6, 6]
  num_heads: [3, 6, 8]
  mixer: ['DPB','DPB','DPB','DPB','DPB','DPB','DPB','DPB','DPB','DPB','DPB','DPB','DPB','DPB','DPB']
  local_mixer: [3, 5, 7]
  last_stage: True
  prenorm: True

train:
  epochs: 60
  batch_size: 32
  num_workers: 8
  lr: 0.0002
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.05  # AdamW的权重衰减

test:
  batch_size: 32
  num_workers: 4

path:
  save_dir: "./scc3_checkpoints"